### PR TITLE
Port new ANSI colour code to lua

### PR DESCRIPTION
**Pull request by keneanung**
Some parts of the ANSI colour code in mudlet was changed. To keep the colours in sync, the lua code had to be changed as well.

### CODE REVIEW

**Comment by keneanung** [comment]
After rechecking, I lost confidence in the unit tests from back then. I'd expect some to fail (and after manually checking a particular one, that one should have never passed, if my math is right).

**Comment by keneanung** [comment]
I sometimes hate setting something up in travis T.T So much trial and error... giving up for now

**Comment by vadi2** [comment]
bump.

**Comment by keneanung** [comment]
Oh right, I forgot about this... I'm on vacation right now, but I'll check the tests at home again. But I will revert the travis changes and we should fix it in an isolated issue.

**Comment by SlySven** [comment]
The main application is still being build with Precise Pangolin BTW - but it seems that the last failure on **that** version of the [platform](https://github.com/vadi2/mudlet-lua/pull/11/commits/1764780701126b9c595ca49f3dfa2b267875062e) was possibly caused by using a python of 2.7.9 or less... :confused:

**Comment by keneanung** [comment]
The change of build platform was just an experiment. As I said, I will
revert all changes to the tests and we should take care of them in an extra
issue.

Stephen Lyons <notifications@github.com> schrieb am Di., 29. Mär. 2016
06:16:

**Comment by keneanung** [comment]
Updated this PR by removing al travis experiments. Travis is now failing at setting up busted, but I think we should ignore those for now and merge it in...

**Pull request merged**
